[project]
name = "scene-chart-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "alembic>=1.19.0",
    "fastapi>=0.141.1",
    "psycopg2-binary>=2.9.12",
    "pydantic>=2.13.4",
    "sqlmodel>=0.0.39",
    "uvicorn>=0.52.1",
]
