"""add yesterday_rank to songstreamreport

Revision ID: 2b2ea819209a
Revises: ed1174217765
Create Date: 2026-08-29 02:50:22.761394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b2ea819209a'
down_revision: Union[str, Sequence[str], None] = 'ed1174217765'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songstreamreport', sa.Column('yesterday_rank', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('songstreamreport', 'yesterday_rank')
    # ### end Alembic commands ###
