"""add report_date to ChartReportSnapshot with index

Revision ID: 45b97f606b5d
Revises: c610e858bd9f
Create Date: 2026-08-14 20:32:34.531935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45b97f606b5d'
down_revision: Union[str, Sequence[str], None] = 'c610e858bd9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chartreportsnapshot', sa.Column('report_date', sa.Date(), nullable=False))
    op.create_index('ix_chartreportsnapshot_song_report_date', 'chartreportsnapshot', ['song_id', 'report_date', 'recent_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_chartreportsnapshot_song_report_date', table_name='chartreportsnapshot')
    op.drop_column('chartreportsnapshot', 'report_date')
    # ### end Alembic commands ###
