"""alter rank_day to date required

Revision ID: 6af2517900cc
Revises: ab93a4e93b84
Create Date: 2026-08-27 10:39:04.800502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6af2517900cc'
down_revision: Union[str, Sequence[str], None] = 'ab93a4e93b84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        DO $$
        BEGIN
            IF EXISTS (
                SELECT 1
                FROM songchartsnapshot
                WHERE rank_day IS NULL
                   OR (
                       rank_day !~ '^\\d{4}-\\d{2}-\\d{2}$'
                       AND rank_day !~ '^\\d{4}\\.\\d{2}\\.\\d{2}$'
                       AND rank_day !~ '^\\d{8}$'
                   )
            ) THEN
                RAISE EXCEPTION
                    'Invalid rank_day value exists. Migration aborted.';
            END IF;
        END
        $$;
        """
    )

    op.execute(
        """
        UPDATE songchartsnapshot
        SET rank_day = CASE
            WHEN rank_day ~ '^\\d{4}\\.\\d{2}\\.\\d{2}$'
                THEN replace(rank_day, '.', '-')
            WHEN rank_day ~ '^\\d{8}$'
                THEN substring(rank_day, 1, 4) || '-'
                     || substring(rank_day, 5, 2) || '-'
                     || substring(rank_day, 7, 2)
            ELSE rank_day
        END
        """
    )

    op.alter_column('songchartsnapshot', 'rank_day',
               existing_type=sa.VARCHAR(),
               type_=sa.Date(),
               nullable=False,
               postgresql_using="rank_day::date")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('songchartsnapshot', 'rank_day',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
