"""add album and song last updated timestamps

Revision ID: 95cf3b3e6cb9
Revises: 9af402b46ae8
Create Date: 2026-08-14 11:07:19.745442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '95cf3b3e6cb9'
down_revision: Union[str, Sequence[str], None] = '9af402b46ae8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('archivechangelog',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('entity_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('entity_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('field_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('old_value', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('new_value', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('album', sa.Column('last_updated_at', sa.DateTime(), nullable=False, server_default=sa.text("CURRENT_TIMESTAMP")))
    op.add_column('song', sa.Column('last_updated_at', sa.DateTime(), nullable=False, server_default=sa.text("CURRENT_TIMESTAMP")))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('song', 'last_updated_at')
    op.drop_column('album', 'last_updated_at')
    op.drop_table('archivechangelog')
    # ### end Alembic commands ###
