"""initial

Revision ID: 9af402b46ae8
Revises: 
Create Date: 2026-08-07 15:54:54.004687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9af402b46ae8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS pgcrypto')
    op.create_table('album',
    sa.Column('album_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('issue_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('song_count', sa.Integer(), nullable=True),
    sa.Column('content_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('album_id')
    )
    op.create_table('artist',
    sa.Column('artist_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('debut_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('nationality', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('gender', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('act_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('act_genre', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('company_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('intro', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('artist_id')
    )
    op.create_table('albumartist',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('album_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('artist_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['album_id'], ['album.album_id'], ),
    sa.ForeignKeyConstraint(['artist_id'], ['artist.artist_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('album_id', 'artist_id')
    )
    op.create_index(op.f('ix_albumartist_album_id'), 'albumartist', ['album_id'], unique=False)
    op.create_index(op.f('ix_albumartist_artist_id'), 'albumartist', ['artist_id'], unique=False)
    op.create_table('artistmember',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('artist_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('member_artist_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('member_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('act_type_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('debut_day', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('birthday', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['artist.artist_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('artist_id', 'member_artist_id')
    )
    op.create_index(op.f('ix_artistmember_artist_id'), 'artistmember', ['artist_id'], unique=False)
    op.create_table('artistsnapshot',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('artist_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('current_rank', sa.Integer(), nullable=False),
    sa.Column('past_rank', sa.Integer(), nullable=False),
    sa.Column('rank_gap', sa.Integer(), nullable=False),
    sa.Column('top_rank', sa.Integer(), nullable=False),
    sa.Column('past_week_rank', sa.Integer(), nullable=False),
    sa.Column('total_fan_count', sa.Integer(), nullable=False),
    sa.Column('increment_fan_count', sa.Integer(), nullable=False),
    sa.Column('increment_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('song_index', sa.Float(), nullable=False),
    sa.Column('mv_index', sa.Float(), nullable=False),
    sa.Column('photo_index', sa.Float(), nullable=False),
    sa.Column('fan_index', sa.Float(), nullable=False),
    sa.Column('like_index', sa.Float(), nullable=False),
    sa.Column('toc_index', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artist.artist_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_artistsnapshot_artist_fetched', 'artistsnapshot', ['artist_id', 'fetched_at'], unique=False)
    op.create_table('magazine',
    sa.Column('content_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('artist_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artist.artist_id'], ),
    sa.PrimaryKeyConstraint('content_id')
    )
    op.create_index(op.f('ix_magazine_artist_id'), 'magazine', ['artist_id'], unique=False)
    op.create_table('photo',
    sa.Column('photo_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('artist_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('photo_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artist.artist_id'], ),
    sa.PrimaryKeyConstraint('photo_id')
    )
    op.create_index(op.f('ix_photo_artist_id'), 'photo', ['artist_id'], unique=False)
    op.create_table('song',
    sa.Column('song_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('album_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('play_time', sa.Integer(), nullable=True),
    sa.Column('issue_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_title_song', sa.Boolean(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['album_id'], ['album.album_id'], ),
    sa.PrimaryKeyConstraint('song_id')
    )
    op.create_index(op.f('ix_song_album_id'), 'song', ['album_id'], unique=False)
    op.create_table('video',
    sa.Column('mv_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('artist_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('song_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('issue_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artist.artist_id'], ),
    sa.PrimaryKeyConstraint('mv_id')
    )
    op.create_index(op.f('ix_video_artist_id'), 'video', ['artist_id'], unique=False)
    op.create_table('chartreportsnapshot',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('song_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('recent_time', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('current_rank', sa.Integer(), nullable=False),
    sa.Column('past_rank', sa.Integer(), nullable=False),
    sa.Column('rank_gap', sa.Integer(), nullable=False),
    sa.Column('rank_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('listener_one_hour', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('listener_one_day', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['song_id'], ['song.song_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chartreportsnapshot_song_fetched', 'chartreportsnapshot', ['song_id', 'fetched_at'], unique=False)
    op.create_table('graphpoint',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('song_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('resolution', sa.Enum('hourly', 'five_min', name='graphresolution'), nullable=False),
    sa.Column('fetch_batch_at', sa.DateTime(), nullable=False),
    sa.Column('x', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['song_id'], ['song.song_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_graphpoint_song_resolution_batch', 'graphpoint', ['song_id', 'resolution', 'fetch_batch_at'], unique=False)
    op.create_table('songartist',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('song_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('artist_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('credited_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artist.artist_id'], ),
    sa.ForeignKeyConstraint(['song_id'], ['song.song_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('song_id', 'artist_id')
    )
    op.create_index(op.f('ix_songartist_artist_id'), 'songartist', ['artist_id'], unique=False)
    op.create_index(op.f('ix_songartist_song_id'), 'songartist', ['song_id'], unique=False)
    op.create_table('songchartsnapshot',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('song_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('chart_type', sa.Enum('realtime', 'top100', 'daily', 'weekly', 'hot100', name='charttype'), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('rank_day', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('rank_hour', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('current_rank', sa.Integer(), nullable=False),
    sa.Column('past_rank', sa.Integer(), nullable=False),
    sa.Column('rank_gap', sa.Integer(), nullable=False),
    sa.Column('rank_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['song_id'], ['song.song_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_songchartsnapshot_song_chart_fetched', 'songchartsnapshot', ['song_id', 'chart_type', 'fetched_at'], unique=False)
    op.create_table('videoviewsnapshot',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mv_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mv_id'], ['video.mv_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_videoviewsnapshot_mv_fetched', 'videoviewsnapshot', ['mv_id', 'fetched_at'], unique=False)
    op.create_table('rankhistorypoint',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('report_snapshot_id', sa.Uuid(), nullable=False),
    sa.Column('is_predicted', sa.Boolean(), nullable=False),
    sa.Column('x_index', sa.Integer(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['report_snapshot_id'], ['chartreportsnapshot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rankhistorypoint_report_snapshot_id'), 'rankhistorypoint', ['report_snapshot_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rankhistorypoint_report_snapshot_id'), table_name='rankhistorypoint')
    op.drop_table('rankhistorypoint')
    op.drop_index('ix_videoviewsnapshot_mv_fetched', table_name='videoviewsnapshot')
    op.drop_table('videoviewsnapshot')
    op.drop_index('ix_songchartsnapshot_song_chart_fetched', table_name='songchartsnapshot')
    op.drop_table('songchartsnapshot')
    op.drop_index(op.f('ix_songartist_song_id'), table_name='songartist')
    op.drop_index(op.f('ix_songartist_artist_id'), table_name='songartist')
    op.drop_table('songartist')
    op.drop_index('ix_graphpoint_song_resolution_batch', table_name='graphpoint')
    op.drop_table('graphpoint')
    op.drop_index('ix_chartreportsnapshot_song_fetched', table_name='chartreportsnapshot')
    op.drop_table('chartreportsnapshot')
    op.drop_index(op.f('ix_video_artist_id'), table_name='video')
    op.drop_table('video')
    op.drop_index(op.f('ix_song_album_id'), table_name='song')
    op.drop_table('song')
    op.drop_index(op.f('ix_photo_artist_id'), table_name='photo')
    op.drop_table('photo')
    op.drop_index(op.f('ix_magazine_artist_id'), table_name='magazine')
    op.drop_table('magazine')
    op.drop_index('ix_artistsnapshot_artist_fetched', table_name='artistsnapshot')
    op.drop_table('artistsnapshot')
    op.drop_index(op.f('ix_artistmember_artist_id'), table_name='artistmember')
    op.drop_table('artistmember')
    op.drop_index(op.f('ix_albumartist_artist_id'), table_name='albumartist')
    op.drop_index(op.f('ix_albumartist_album_id'), table_name='albumartist')
    op.drop_table('albumartist')
    op.drop_table('artist')
    op.drop_table('album')
    # ### end Alembic commands ###
