"""add song_chart_ranktime index to songchartsnapshot

Revision ID: ab93a4e93b84
Revises: af2a57388908
Create Date: 2026-08-26 00:59:06.410468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab93a4e93b84'
down_revision: Union[str, Sequence[str], None] = 'af2a57388908'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_songchartsnapshot_song_chart_ranktime', 'songchartsnapshot', ['song_id', 'chart_type', 'rank_day', 'rank_hour'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_songchartsnapshot_song_chart_ranktime', table_name='songchartsnapshot')
    # ### end Alembic commands ###
