"""alter male_percent, female_percent from int to decimal

Revision ID: ae57b8598e6d
Revises: 2b2ea819209a
Create Date: 2026-09-01 04:50:21.218395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae57b8598e6d'
down_revision: Union[str, Sequence[str], None] = '2b2ea819209a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('songstreamreport', 'male_percent',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=4, scale=1),
               existing_nullable=True)
    op.alter_column('songstreamreport', 'female_percent',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=4, scale=1),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('songstreamreport', 'female_percent',
               existing_type=sa.Numeric(precision=4, scale=1),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('songstreamreport', 'male_percent',
               existing_type=sa.Numeric(precision=4, scale=1),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
