"""add point_at instead of x index to GraphPoint

Revision ID: c610e858bd9f
Revises: 95cf3b3e6cb9
Create Date: 2026-08-14 19:32:48.786488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c610e858bd9f'
down_revision: Union[str, Sequence[str], None] = '95cf3b3e6cb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('graphpoint', sa.Column('point_at', sa.DateTime(), nullable=False))
    op.drop_column('graphpoint', 'x')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('graphpoint', sa.Column('x', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('graphpoint', 'point_at')
    # ### end Alembic commands ###
