"""add songstreamreport table

Revision ID: ed1174217765
Revises: 6af2517900cc
Create Date: 2026-08-28 23:39:56.572937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ed1174217765'
down_revision: Union[str, Sequence[str], None] = '6af2517900cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('songstreamreport',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('song_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('daily_listener_count', sa.Integer(), nullable=True),
    sa.Column('total_listen_count', sa.Integer(), nullable=True),
    sa.Column('total_listener_count', sa.Integer(), nullable=True),
    sa.Column('male_percent', sa.Integer(), nullable=True),
    sa.Column('female_percent', sa.Integer(), nullable=True),
    sa.Column('age_percent', sa.ARRAY(sa.INTEGER()), nullable=True),
    sa.ForeignKeyConstraint(['song_id'], ['song.song_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('song_id', 'report_date', name='uq_song_stream_report_song_date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('songstreamreport')
    # ### end Alembic commands ###
