services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    command:  >
      sh -c "uv run --no-sync alembic upgrade head && uv run --no-sync uvicorn src.app:app --host 0.0.0.0 --port 8000"
    environment:
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}
    restart: unless-stopped
  scheduler:
    build:
      context: .
      dockerfile: docker/scheduler/Dockerfile
    environment:
      TZ: Asia/Seoul
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}
      WEBHOOK_URL: ${WEBHOOK_URL}
      FRONTEND_HOSTS: ${FRONTEND_HOSTS}
    volumes:
      - ./data/log/app:/app/logs
      - ./data/cursor:/app/cursor
      - ./crontab:/app/crontab:ro
    command: ["supercronic", "/app/crontab"]
    restart: unless-stopped
  nginx:
    image: nginx:1.28.3
    environment:
      DOMAIN: ${DOMAIN}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/log/nginx:/var/log/nginx
      - ./nginx:/etc/nginx/templates:ro
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/www/certbot
    depends_on:
      - app
    restart: unless-stopped
  certbot:
    image: certbot/certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/www/certbot
    environment:
      DOMAIN: ${DOMAIN}
      EMAIL: ${EMAIL}
    depends_on:
      - nginx
    entrypoint: >
      sh -c "while true; do certbot renew --non-interactive --webroot -w /var/www/certbot --quiet; sleep 12h; done"

volumes:
  certbot-etc:
  certbot-var:
